url: https://sidpic.github.io
baseurl: /
title: 'SidPic'
excerpt_separator: <!--more--->
paginate: 5
paginate_path: "/news/page:num/"
plugins:
    - jekyll-paginate
    - jekyll-feed
    - jekyll-sitemap
    - jekyll-seo-tag

socials:
    - name:     "VK"
      url:      "https://vk.com/spicmusic"
      icon:     "/icons/vk.png"

    - name:     "YouTube"
      url:      "https://www.youtube.com/@sidpiclu"
      icon:     "/icons/yt.png"

#~ streamings:
    #~ - name:
      #~ url:
      #~ icon:

# муз. теги
#   депрессивная печальная светлая жизнерадостная
#   легкая умеренная напряженная агрессивная
#   простая сказочная мистическая вычурная
#   интимная мечтательная чувственная пафосная

music:
    - name:     "Танец"
      tags:     ["легкая", "светлая", "простая", "мечтательная"]
      buy:      https://musicat.store/authors/limensid
      url:      "https://s1034sas.storage.yandex.net/rdisk/0696b3f4837020f5b739d3219976ff6f9eab20db0feac191bfe480b607f4ae20/66eaff45/aj1FhYyDHrJilfbT_On5b-nLfBmvq3rAIZJq_cXoXB8KsM8K9wFVY5tgWt6wxMQ7g-88tq2UFjdJBVHDzbswjA==?uid=0&filename=%D0%A2%D0%B0%D0%BD%D0%B5%D1%86.mp3&disposition=attachment&hash=EhYVO8n7Ab7KoaY2Z2kdRndpoh0bXNzlr4qkl3mYBdxPVIVrayEqalahqlRySe4dq/J6bpmRyOJonT3VoXnDag%3D%3D&limit=0&content_type=audio%2Fmpeg&owner_uid=1905780339&fsize=2500621&hid=2367aae5b7c64b3ef0001a1877f1490d&media_type=audio&tknv=v2&ts=62267459a9b40&s=4bd6efce56762d2f1c043d749ccc97ae88cafd09d9cf95b52d53ae0deaea117d&pb=U2FsdGVkX19aRiH9m0aWB0A-Sx6qHemaI75OBuoltMPa2PBbB2v_UZzILPC0d64Z2kBnRFTwaJEWpFnXDciPWbTde0K39bCacML_8CEhscI"
      cover:    "https://s717sas.storage.yandex.net/rdisk/ca13360cf530aea5252b6d179924f78767284143be504663974118a39677a309/66eaff29/aj1FhYyDHrJilfbT_On5b8CS9f16Y94YecH2fvlIanMVBJX1j3dZSQPAXynoT5jd477lzzqooF3bubNcwK0zZg==?uid=0&filename=Танец.webp&disposition=inline&hash=&limit=0&content_type=image%2Fwebp&owner_uid=0&fsize=9424&hid=e91f10ee588e6d88d96a8f7edf69f491&media_type=image&tknv=v2&etag=ec3c4e9d7b492f30b71786b3015c99eb&ts=6226743ef5c40&s=fcc87fc0a73d6b2cf81664be54cef17646b4d4cc804c817d9536ae465d7923f9&pb=U2FsdGVkX19Pb0XgcrVg_l9AtUXD89ptqOwyRdZn5s1x3U1ntP-m9FsK0RMXbee074SVBVDzoxX1QaskX3PRIwH80Xnc0-TWIWVFiZCSMlg"

    - name:     "Данко I"
      tags:     ["жизнерадостная", "напряженная", "легкая", "агрессивная", "сказочная"]
      buy:      https://musicat.store/authors/limensid
      url:      "https://s166vlx.storage.yandex.net/rdisk/7d73dfe5193fda03871744d18c48fb52175f5883e64a752935a93538ce1bee7a/66eb01df/aj1FhYyDHrJilfbT_On5b-FIuvot2_y8fGFSHovtViycolzoppBAe04NU5dAT6lcWtTSvPYdbJDUeufBKpDzHw==?uid=0&filename=%D0%94%D0%B0%D0%BD%D0%BA%D0%BE%20I.mp3&disposition=attachment&hash=BWwizdZbCy9jFVJlMeXUKDayD07j8XstuFbWGgPw4kC6IRYXDUhDYF4PIQ%2BwgjRTq/J6bpmRyOJonT3VoXnDag%3D%3D&limit=0&content_type=audio%2Fmpeg&owner_uid=1905780339&fsize=3161062&hid=efff24aae0aa1ee21b2f10a03b97272f&media_type=audio&tknv=v2&ts=622676d4cf5c0&s=c0e0e8209d8708ffc1e2f831766c7fc1ba84b4889fc8d48e5ac588c260dd7d0d&pb=U2FsdGVkX1_-_90RA3rHLRJHKvJSKKMbGgbE5gyP46-8sjqgfCC-eDnT_OV63s9HC4T2AKG66T-WHOJgDvgol9VMFFFlPSPN1ZnOoQdJLi8"
      cover:    "https://download.sberdisk.ru/download/file/519823693?token=8rIuJ4YD5HBZiJ5&filename=Данко%20I.webp"

    - name:     "Марш деревянных солдатиков"
      tags:     ["светлая", "печальная", "умеренная", "сказочная", "мечтательная"]
      buy:      https://musicat.store/catalog/marsh-dereviannykh-soldatikov
      url:      "https://download.sberdisk.ru/download/file/518069708?token=4qt4mZ2G7Gqba2x&filename=Марш%20деревянных%20солдатиков.mp3"
      cover:    "https://download.sberdisk.ru/download/file/518069793?token=dpOhVrlOG6nb6kP&filename=Марш%20деревянных%20солдатиков.webp"

    - name:     "Проекция"
      tags:     ["светлая", "умеренная", "простая", "чувственная"]
      buy:      https://musicat.store/catalog/proektsiia
      url:      "https://download.sberdisk.ru/download/file/516421865?token=DoVxWVQ36LjWVsw&filename=Проекция.mp3"
      cover:    "https://download.sberdisk.ru/download/file/516091950?token=yCQsibSd5bmhEBI&filename=Проекция.webp"

    - name:     "D"
      tags:     ["напряженная", "мистическая"]
      buy:      https://musicat.store/catalog/d
      url:      "https://download.sberdisk.ru/download/file/516421863?token=xwL6hsyNwcO1iUU&filename=D.mp3"
      cover:    "https://download.sberdisk.ru/download/file/516421937?token=fsfxmccRPNeZo2r&filename=D.webp"

    - name:     "А"
      tags:     ["светлая", "напряженная", "простая", "интимная"]
      buy:      https://musicat.store/catalog/a
      url:      "https://download.sberdisk.ru/download/file/516421864?token=TkhimsACJ67qxpG&filename=А.mp3"
      cover:    "https://download.sberdisk.ru/download/file/516421938?token=QoVd0v5ossli1xI&filename=A.webp"
