url: https://sidpic.github.io
baseurl: /
title: 'SidPic'
excerpt_separator: <!--more--->
paginate: 5
paginate_path: "/news/page:num/"
plugins:
    - jekyll-paginate

socials:
    - name:     "VK"
      url:      "https://vk.com/spicmusic"
      icon:     "/icons/vk.png"

#~ streamings:
    #~ - name:
      #~ url:
      #~ icon:

# муз. теги
#   депрессивная печальная светлая жизнерадостная
#   легкая умеренная напряженная агрессивная
#   простая сказочная мистическая вычурная
#   интимная мечтательная чувственная пафосная

music:
    - name:     "Марш деревянных солдатиков"
      tags:     ["светлая", "печальная", "умеренная", "сказочная", "мечтательная"]
      buy:      https://musicat.store/authors/limensid
      url:      "https://download.sberdisk.ru/download/file/518069708?token=4qt4mZ2G7Gqba2x&filename=Марш%20деревянных%20солдатиков%20(2).mp3"
      cover:    "https://download.sberdisk.ru/download/file/518069793?token=dpOhVrlOG6nb6kP&filename=Марш%20деревянных%20солдатиков.webp"
    - name:     "Проекция"
      tags:     ["светлая", "умеренная", "простая", "чувственная"]
      buy:      https://musicat.store/catalog/proektsiia
      url:      "https://download.sberdisk.ru/download/file/516421865?token=DoVxWVQ36LjWVsw&filename=Проекция.mp3"
      cover:    "https://download.sberdisk.ru/download/file/516091950?token=yCQsibSd5bmhEBI&filename=Проекция.webp"
    - name:     "D"
      tags:     ["напряженная", "мистическая"]
      buy:      https://musicat.store/catalog/d
      url:      "https://download.sberdisk.ru/download/file/516421863?token=xwL6hsyNwcO1iUU&filename=D.mp3"
      cover:    "https://download.sberdisk.ru/download/file/516421937?token=fsfxmccRPNeZo2r&filename=D.webp"
    - name:     "А"
      tags:     ["светлая", "напряженная", "простая", "интимная"]
      buy:      https://musicat.store/catalog/a
      url:      "https://download.sberdisk.ru/download/file/516421864?token=TkhimsACJ67qxpG&filename=А.mp3"
      cover:    "https://download.sberdisk.ru/download/file/516421938?token=QoVd0v5ossli1xI&filename=A.webp"
