theme: jekyll-theme-minimal
title: SidPic
description: Здесь моя музыка и другие проекты, плюс всякие записки.
 Можно слушать музыку, заказать новую или купить готовую для коммерческого использования.
e-mail: sidpiclu@gmail.com
