url: https://sidpic.github.io
baseurl: /
title: 'SidPic'
locale: 'ru_RU'
excerpt_separator: <!--more--->
paginate: 5
paginate_path: "/news/page:num/"
plugins:
    - jekyll-paginate
    - jekyll-feed
    - jekyll-sitemap
    - jekyll-seo-tag

socials:
    - name:     "VK"
      url:      "https://vk.com/spicmusic"
      icon:     "/icons/vk.png"

    - name:     "YouTube"
      url:      "https://www.youtube.com/@sidpiclu"
      icon:     "/icons/yt.png"

#~ streamings:
    #~ - name:
      #~ url:
      #~ icon:

# муз. теги
#   депрессивная печальная светлая жизнерадостная
#   легкая умеренная напряженная агрессивная
#   простая сказочная мистическая вычурная
#   интимная мечтательная чувственная пафосная

music:
    - name:     "Данко II"
      tags:     ["депрессивная", "напряженная", "сказочная"]
      buy:      "https://musicat.store/authors/limensid"
      url:      "https://download.sberdisk.ru/download/file/530837765?token=TmawkUzpkD9DZ5H&filename=Данко%20II.mp3"
      cover:    "https://download.sberdisk.ru/download/file/530837277?token=1knwuSgBWFWtrKm&filename=Данко%20II.webp"
      player:   "https://bandcamp.com/EmbeddedPlayer/track=1675131278/size=large/bgcol=ffffff/linkcol=ffffff/minimal=true/transparent=true/"

    - name:     "Башкирская элегия"
      tags:     ["печальная", "светлая", "умеренная", "простая", "мечтательная"]
      buy:      "https://musicat.store/authors/limensid"
      url:      "https://download.sberdisk.ru/download/file/530837769?token=QbVFT1tNk5KV10X&filename=Башкирская%20элегия.mp3"
      cover:    "https://download.sberdisk.ru/download/file/530837279?token=GbeaSO6W9Rl9FZs&filename=Башкирская%20элегия.webp"
      player:   "https://bandcamp.com/EmbeddedPlayer/track=1898710029/size=large/bgcol=ffffff/linkcol=ffffff/minimal=true/transparent=true/"

    - name:     "Моя любимая погода"
      tags:     ["светлая", "напряженная", "вычурная", "чувственная"]
      buy:      https://musicat.store/authors/limensid
      url:      "https://download.sberdisk.ru/download/file/525714767?token=WesYkZsD92ne39s&filename=Моя%20любимая%20погода.mp3"
      cover:    "https://download.sberdisk.ru/download/file/525714226?token=NO1XqeZnN4JDIrp&filename=Моя_любимая_погода.webp"
      player:   "https://bandcamp.com/EmbeddedPlayer/track=3712946583/size=large/bgcol=ffffff/linkcol=ffffff/minimal=true/transparent=true/"

    - name:     "Танец"
      tags:     ["легкая", "светлая", "простая", "мечтательная"]
      buy:      https://musicat.store/authors/limensid
      url:      "https://download.sberdisk.ru/download/file/530837766?token=rWCTJh9Y6vgZYQe&filename=Танец.mp3"
      cover:    "https://download.sberdisk.ru/download/file/523183954?token=M4bwPwscqz2oxD8&filename=Танец.webp"
      player:   "https://bandcamp.com/EmbeddedPlayer/track=3272085086/size=large/bgcol=ffffff/linkcol=ffffff/minimal=true/transparent=true/"

    - name:     "Данко I"
      tags:     ["жизнерадостная", "напряженная", "легкая", "агрессивная", "сказочная"]
      buy:      https://musicat.store/authors/limensid
      url:      "https://download.sberdisk.ru/download/file/519824472?token=QQklkbD79BnXqGG&filename=Данко%20I%20(2).mp3"
      cover:    "https://download.sberdisk.ru/download/file/519823693?token=8rIuJ4YD5HBZiJ5&filename=Данко%20I.webp"
      player:   "https://bandcamp.com/EmbeddedPlayer/track=2150997095/size=large/bgcol=ffffff/linkcol=ffffff/minimal=true/transparent=true"

    - name:     "Марш деревянных солдатиков"
      tags:     ["светлая", "печальная", "умеренная", "сказочная", "мечтательная"]
      buy:      https://musicat.store/catalog/marsh-dereviannykh-soldatikov
      url:      "https://download.sberdisk.ru/download/file/518069708?token=4qt4mZ2G7Gqba2x&filename=Марш%20деревянных%20солдатиков.mp3"
      cover:    "https://download.sberdisk.ru/download/file/518069793?token=dpOhVrlOG6nb6kP&filename=Марш%20деревянных%20солдатиков.webp"
      player:   "https://bandcamp.com/EmbeddedPlayer/track=1756819209/size=large/bgcol=ffffff/linkcol=ffffff/minimal=true/transparent=true/"

    - name:     "Проекция"
      tags:     ["светлая", "умеренная", "простая", "чувственная"]
      buy:      https://musicat.store/catalog/proektsiia
      url:      "https://download.sberdisk.ru/download/file/516421865?token=DoVxWVQ36LjWVsw&filename=Проекция.mp3"
      cover:    "https://download.sberdisk.ru/download/file/516091950?token=yCQsibSd5bmhEBI&filename=Проекция.webp"
      player:   "https://bandcamp.com/EmbeddedPlayer/track=349605822/size=large/bgcol=ffffff/linkcol=ffffff/minimal=true/transparent=true/"

    - name:     "D"
      tags:     ["напряженная", "мистическая"]
      buy:      https://musicat.store/catalog/d
      url:      "https://download.sberdisk.ru/download/file/516421863?token=xwL6hsyNwcO1iUU&filename=D.mp3"
      cover:    "https://download.sberdisk.ru/download/file/516421937?token=fsfxmccRPNeZo2r&filename=D.webp"
      player:   "https://bandcamp.com/EmbeddedPlayer/track=2718242498/size=large/bgcol=ffffff/linkcol=ffffff/minimal=true/transparent=true/"

    - name:     "А"
      tags:     ["светлая", "напряженная", "простая", "интимная"]
      buy:      https://musicat.store/catalog/a
      url:      "https://download.sberdisk.ru/download/file/516421864?token=TkhimsACJ67qxpG&filename=А.mp3"
      cover:    "https://download.sberdisk.ru/download/file/516421938?token=QoVd0v5ossli1xI&filename=A.webp"
      player:   "https://bandcamp.com/EmbeddedPlayer/track=1466684712/size=large/bgcol=ffffff/linkcol=ffffff/minimal=true/transparent=true/"
